# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: Survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v


features:
  - PassengerId
  - Pclass
  - Name
  - Sex
  - Age
  - SibSp
  - Parch
  - Ticket
  - Fare
  - Cabin
  - Embarked


# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

C: 0.0005

drop_features:
  - PassengerId
  - Name
  - Ticket
  
categorical_vars_with_na_missing:
  - Sex
  - Cabin
  - Embarked

categorical_vars_with_extraction:
  - Cabin

numerical_vars_with_na:
  - Age
  - Fare

categorical_vars:
  - Sex
  - Cabin
  - Embarked
